FROM node:20-bookworm

ARG VITE_API_BASE_URL
ARG VITE_API_WS_URL
ENV VITE_API_BASE_URL=$VITE_API_BASE_URL
ENV VITE_API_WS_URL=$VITE_API_WS_URL

RUN apt update -y && apt upgrade -y && apt install -y \
    && apt clean

WORKDIR /app

COPY ./app .

RUN npm install && npm run build && npm install -g serve

EXPOSE 3000

CMD ["npm", "run", "preview"]
