services:
  opensearch-node:
    image: opensearchproject/opensearch:2.11.1
    container_name: opensearch-node
    # On active 'init: true' pour utiliser tini en tant que PID 1
    # Cela permet de bien gérer la propagation des signaux SIGINT/SIGTERM
    # et d’éviter les longs délais à l’arrêt du conteneur.
    init: true
    environment:
      - discovery.type=single-node
      - "DISABLE_SECURITY_PLUGIN=true"
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "${OPENSEARCH_PORT:-9200}:9200"
      - "${OPENSEARCH_MONITORING_PORT:-9600}:9600"
    volumes:
      - opensearch-data:/usr/share/opensearch/data

  fastapi-backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: fastapi-backend
    ports:
      - "${FASTAPI_PORT:-8000}:${FASTAPI_PORT:-8000}"
    volumes:
      - ./backend/app:/app
    env_file:
      - .env
    depends_on:
      - opensearch-node

volumes:
  opensearch-data:
